/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DesignPattern;
//import static org.junit.Assert.*;

public class AppTest {
    public void appHasAGreeting() {
      //  App classUnderTest = new App();
       // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
